#!/bin/sh
#
# This tool is a piece of evil magic, which allows one to cross-bootstrap
# target userlands inside of Slind development chroot. Invocation format is:
#
#   cross-shell arch command_args
#
#   Executes single command in context of target rootfs, command_args is the
#   command to be executed
#
set -e

. /etc/cross-shell/config
. /usr/share/cross-shell/shared-mounts

usage() {
    echo "Usage: cross-shell <arch> <command ....>"
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

# Backward compatibility
if  [ "$1" = sh ]; then
    echo "Warning: using deprecated 'cross-shell sh' syntax" >&2
    shift
fi

ARCH=$1
shift

WHERE=/rootfs-$ARCH

if ! [ -d $WHERE ]; then
    echo "rootfs directory does not exist: $WHERE."
    exit 1
fi

HOSTARCH=$(dpkg --print-architecture)
FAKECHROOT_CROSS=/rootfs-$HOSTARCH
CROSS_SHELL_ARCH=$ARCH
PATH=/usr/sbin:/sbin:${PATH}
LD_PRELOAD=/usr/lib/fakechroot-cross/libfakechroot-cross.so:/usr/lib/libfakeroot/libfakeroot-sysv.so

export CROSS_SHELL_ARCH PATH FAKECHROOT_CROSS LD_PRELOAD

try_bind_mount /var/cache/apt/archives-$ARCH $WHERE/var/cache/apt/archives

case $HOSTARCH in
    i386)  DYLINKER=/lib/ld-linux.so.2;;
    amd64) DYLINKER=/lib/ld-linux-x86-64.so.2;;
    *)     echo "Unknown dynamic linker for $HOSTARCH" >&2; exit 1;;
esac

$FAKECHROOT_CROSS$DYLINKER --library-path $FAKECHROOT_CROSS/usr/local/lib:$FAKECHROOT_CROSS/lib:$FAKECHROOT_CROSS/usr/lib $FAKECHROOT_CROSS/bin/busybox chroot $WHERE "$@"
